# 夹爪参数,最大开度和最小开度
grispper:
  max_width: 0.05
  min_width: 0.0

# 计算夹爪距离时的默认alpha值
grisp_distance_alpha: 0.05

# 默认的摩擦系数
default_friction_coef: 0.5

# 计算摩擦锥时的默认多面体近似面数
num_cone_faces: 8

# 稳定姿态阈值
stable_pose_min_p: 0.0

# 接触点之间容许的最小宽度
min_contact_dist: 0.0025

# 不同抓取点之间的容许的最小距离
grasp_dist_thresh: 0.0005

# 每个物体采样的数目
num_sample: 25

metrics:
  quality_method: ferrari_canny_L1
  friction_coef: 0.5
  num_cone_faces: 8
  soft_fingers: 1
  all_contacts_required: 1

  # optional deterministic parameters
  torque_scaling: 1000
  wrench_norm_thresh: 0.001
  wrench_regularizer: 0.0000000001

  # 夹爪参数
  finger_radius: 0.01
  force_limits: 20.0

# 碰撞检测器配置
collision_checker:
  # 宽度补偿, 假设夹爪存在一定的宽度, 即夹爪的横向宽度
  width_offset: 0.005
  # 深度补偿, 在夹爪抓取路径方向上进行补偿
  depth_offiset: 0.005
  # 轴向补偿: 在抓取轴方向上进行补偿
  axis_offiset: 0.005
  # 检测点数目
  checker_point_num: 5
  # 检查距离
  test_dist: 0.5


auto_render_images: 0

# 相机的参数
camera:
  # 相机可视角度
  min_yfov: 60
  max_yfov: 70
  # 相机纵横比
  aspectRatio: 1.0
  # 相机模型投影近平面距离,即焦距
  min_znear: 0.05
  max_znear: 0.07
  # 相机离原点的距离
  min_radius: 0.65
  max_radius: 0.75
  # 相机位置与z轴的夹角
  min_elev: 0.1
  max_elev: 5.0 # in degrees
  # 相机位置的方位角, 与x轴的夹角
  min_az: 0.0
  max_az: 360.0 # degrees
  # 相机坐标绕z轴旋转的角度
  min_roll: -0.2
  max_roll: 0.2 # degrees
  # 物体偏离中心的距离, 这里直接转换成相机位置的变换，物体还是放在原点
  # min_x: -0.1
  # max_x: 0.1
  # min_y: -0.1
  # max_y: 0.1
  min_x: 0
  max_x: 0
  min_y: 0
  max_y: 0
  # 渲染的图片的大小
  im_width: 600
  im_height: 600

  obj_color: orange
  table_color: white

  num_radii: 2
  num_elev: 2
  num_az: 8
  num_roll: 1
  min_p: 0.01

env_rv_params:
  # Camera intrinsics
  min_f: 520
  max_f: 530
  min_cx: 299.5
  max_cx: 299.5
  min_cy: 299.5
  max_cy: 299.5
  im_width: 600
  im_height: 600

  # Camera pose


  